### ISSUE TITLE
Chapter 5: azuredeploy.json

### ISSUE THREAD

**Issue by glennatlayla** [PacktPublishing/Designing-and-Implementing-Microsoft-Azure-Networking-Solutions#1]
Hi - when trying to deploy the resources in Chapter05/template/azuredeploy.json, I get the following error message:

{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource 'MyCustomScriptExtension' for type 'Microsoft.Compute/virtualMachines/extensions' at line '548' and column '60' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'."}

**Comment by davidokeyode** [comment]
> Hi - when trying to deploy the resources in Chapter05/template/azuredeploy.json, I get the following error message:
> 
> {"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource 'MyCustomScriptExtension' for type 'Microsoft.Compute/virtualMachines/extensions' at line '548' and column '60' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'."}

@glennatlayla - Apologies for the delay. Issue now fixed in the latest commit. Thanks.
